### PR TITLE
Bonus

### PR DESCRIPTION
**Pull request by Tommytrg**

### CODE REVIEW

**Comment by aesedepece** [comment]
Considering that this repository is now public, it would be just too easy for someone to farm all the bonuses without actually scanning the in situ QR codes, simply by scraping the URLs from the repo.

A safer approach would be to have the generator derive the codes in memory upon construction, off a seed that can be provided through configuration. That is exactly how #35 does on the Python side. @Tommytrg @gabaldon @guidiaz  If that sounds good to you, I can take over this PR and quickly make a follow-up one implementing that logic.

**Comment by Tommytrg** [comment]
> Considering that this repository is now public, it would be just too easy for someone to farm all the bonuses without actually scanning the in situ QR codes, simply by scraping the URLs from the repo.
> 
> A safer approach would be to have the `BonusValidator` derive the codes in memory upon construction, off a seed that can be provided through configuration. That is exactly how #35 does on the Python side. @Tommytrg @gabaldon @guidiaz If that sounds good to you, I can take over this PR and quickly make a follow-up one implementing that logic.

Sounds good to me! We can easily add a new env variable for this and generate the QRs using it

**Comment by aesedepece** [comment]
> > Considering that this repository is now public, it would be just too easy for someone to farm all the bonuses without actually scanning the in situ QR codes, simply by scraping the URLs from the repo.
> > A safer approach would be to have the `BonusValidator` derive the codes in memory upon construction, off a seed that can be provided through configuration. That is exactly how #35 does on the Python side. @Tommytrg @gabaldon @guidiaz If that sounds good to you, I can take over this PR and quickly make a follow-up one implementing that logic.
> 
> Sounds good to me! We can easily add a new env variable for this and generate the QRs using it

I'm even thinking of using the same one, provided that the player index to player ID generator function in my Python PR already namespaces bonus codes so they don't collide with players. I.e. player 123 and bonus 123 won't have the same ID.

**Comment by Tommytrg** [comment]
Superseded by #51

**Pull request closed without merging**
